### ISSUE TITLE
New Users Logging into Page Not Found

### ISSUE THREAD

**Issue by KupaaSolutions** [piranha771/unraid-templates#3]
Fresh install, encountering error when new users login and receive page not found error.
Admin user does not have this issue, only non admin accounts.

Template was deployed, no issues reported from users for 3 days then began to see the issue.

"**_Page unavailable
Sorry, but the requested page is unavailable due to a server hiccup.

Our engineers have been notified, so check back later._**"

**Comment by piranha771** [comment]
The login page is always functional?
Can you show me a server log with one of those failed requests?
What is the exact url that is requested?
There is the possibility that this is not a dockerman issue but some issue inside seafile. Consider contacting seafile directly.

**Comment by KupaaSolutions** [comment]
The issue has escalated to it no longer being able to connect to the database.

MARIA DB:
023-02-08 12:50:13 0 [Note] Plugin 'FEEDBACK' is disabled.
2023-02-08 12:50:13 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2023-02-08 12:50:13 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
2023-02-08 12:50:13 0 [Note] Server socket created on IP: '0.0.0.0'.
2023-02-08 12:50:13 0 [Note] Server socket created on IP: '::'.
2023-02-08 12:50:14 0 [Note] mariadbd: ready for connections.
Version: '10.10.3-MariaDB-1:10.10.3+maria~ubu2204'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2023-02-08 12:50:14 0 [Note] InnoDB: Buffer pool(s) load completed at 230208 12:50:14
2023-02-08 12:50:59 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'seafile' host: '172.18.0.4' (Got an error reading communication packets)

SEAFILE:
*** Running /etc/my_init.d/01_create_data_links.sh...
*** Booting runit daemon...
*** Runit started as PID 23
*** Running /scripts/enterpoint.sh...
[2023-02-08 12:49:42] Skip running setup-seafile-mysql.py because there is existing seafile-data folder.
Traceback (most recent call last):
  File "/scripts/start.py", line 92, in <module>
    main()
  File "/scripts/start.py", line 77, in main
    call('{} start'.format(get_script('seafile.sh')))
  File "/scripts/utils.py", line 70, in call
    return subprocess.check_call(*a, **kw)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/seafile/seafile-server-9.0.10/seafile.sh start' returned non-zero exit status 255.
*** Shutting down /scripts/enterpoint.sh (PID 24)...
*** Shutting down runit daemon (PID 23)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
*** Init system aborted.
*** Killing all processes...
*** Running /etc/my_init.d/01_create_data_links.sh...
*** Booting runit daemon...
*** Runit started as PID 23
*** Running /scripts/enterpoint.sh...
[2023-02-08 12:50:59] Skip running setup-seafile-mysql.py because there is existing seafile-data folder.
Traceback (most recent call last):
  File "/scripts/start.py", line 92, in <module>
    main()
  File "/scripts/start.py", line 77, in main
    call('{} start'.format(get_script('seafile.sh')))
  File "/scripts/utils.py", line 70, in call
    return subprocess.check_call(*a, **kw)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/seafile/seafile-server-9.0.10/seafile.sh start' returned non-zero exit status 255.
2023-02-08 12:49:42 Nginx ready 
2023-02-08 12:49:42 This is an idle script (infinite loop) to keep container running. 
[02/08/2023 12:49:42][upgrade]: The container was recreated, start fix the media symlinks
[02/08/2023 12:49:42][upgrade]: Done

Error: the user running the script ("root") is not the owner of "/shared/seafile/seafile-data" folder, you should use the user "UNKNOWN" to run the script.
2023-02-08 12:50:58 Nginx ready 
2023-02-08 12:50:58 This is an idle script (infinite loop) to keep container running. 

Error: the user running the script ("root") is not the owner of "/shared/seafile/seafile-data" folder, you should use the user "UNKNOWN" to run the script.

**Comment by KupaaSolutions** [comment]
At this point it does look like the issue is on SEAFILES end.

**Comment by piranha771** [comment]
Hello,

from the logs this looks like seafile is sending requests to mariadb that are too large. Please try to add --max-allowed-packet=256M to your mariadb container startup command. And look if mariadb is still complaining about communication packets.
